api_platform:
    title: MonAGIL
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    mapping:
        paths:
            - '%kernel.project_dir%/src/Authentication/UI/Http/Rest/ApiPlatform/'
            - '%kernel.project_dir%/src/User/UI/Http/Rest/ApiPlatform/'
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        multipart: [ 'multipart/form-data' ]

