tls:
  certificates:
    - certFile: /certs/_wildcard.monagil.dev.crt
      keyFile: /certs/_wildcard.monagil.dev.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/_wildcard.monagil.dev.crt
        keyFile: /certs/_wildcard.monagil.dev.key