http:
  routers:
   #frontend:
   #  entryPoints:
   #    - websecure
   #  rule: "Host(`app.monagil.dev`)"
   #  tls: {}
   #  service: frontend

    backend:
      entryPoints:
        - websecure
      rule: "Host(`api.monagil.dev`)"
      tls: {}
      service: backend

  services:
    #frontend:
    #  loadBalancer:
    #    servers:
    #      - url: "http://frontend:4200"

    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"
